
[cursor.style]
shape= "Beam"
blinking = "Never"

[font]
size = 12

[window.dimensions]
columns = 0
lines = 0

[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

[colors.normal]
black = '#191C1D'
red = '#BD6062'
green = '#A3D6A9'
yellow = '#F0DFAF'
blue = '#8FB4D8'
magenta = '#C7A9D9'
cyan = '#B6D7A8'
white = '#CED9D6'

[colors.bright]
black = '#727C7C'
red = '#D18FAF'
green = '#B7CEB0'
yellow = '#BCBCBC'
blue = '#E0CF9F'
magenta = '#C7A9D9'
cyan = '#BBDA97'
white = '#FFFFFF'

[colors.selection]
text = '#000000'
background = '#F0DFAF'


#[font.normal]
#family = "jetbrainsmono nerd font"
#style = "Regular"


[font.normal]
family = "Comic Code"
style = "Medium"


[window.padding]
x = 5
y = 5

[font.offset]
x = -1
y = -1


[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[window]
opacity = 1

