#!/bin/sh

# Change to the yt-local directory
cd yt-local >/dev/null 2>&1

# Source the virtual environment
source venv/bin/activate >/dev/null 2>&1

# Run the server.py script
python server.py >/dev/null 2>&1
