theme = "Default"
default_source = "Nyaa"
download_client = "Transmission"
timeout = 30
scroll_padding = 3
cursor_padding = 4
save_config_on_change = true
hot_reload_config = true

[client.command]
cmd = 'curl "{torrent}" > ~/{file}'
shell_cmd = "sh -c"

[source.nyaa]
base_url = "https://nyaa.si/"
default_sort = "Date"
default_sort_dir = "Desc"
default_filter = "NoFilter"
default_category = "AllCategories"
default_search = ""
rss = false


[client.transmission]
base_url = "http://localhost:9091/transmission/rpc" # required
username = "user" # all optional here and below
password = "pass"
password_file = "/path/to/password.txt"
use_magnet = true
labels = [ # must not contain commas in any of the labels
  "label1",
  "label2"
]
paused = false
peer_limit = 100
bandwidth_priority = "Low"
